### PR TITLE
Updates the circe version to the latest

### PR DESCRIPTION
**Pull request by calvinbrown085**
Circe is on 13.0 now, and it would help to integrate this with the newest version

### CODE REVIEW

**Comment by calvinbrown085** [comment]
@joan38 Any thoughts here?

**Comment by joan38** [comment]
Sorry I missed your PR. Thanks!

**Comment by joan38** [comment]
`0.6.1` released with this and other upgrades

**Comment by calvinbrown085** [comment]
@joan38 No worries!

**Pull request merged**
